export const countries = [
  { name: 'Brasil', code: 'BR', emoji: '🇧🇷', phone: '55' },
  { name: 'Estados Unidos', code: 'US', emoji: '🇺🇸', phone: '1' },
  { name: 'Portugal', code: 'PT', emoji: '🇵🇹', phone: '351' },
  { name: 'Espanha', code: 'ES', emoji: '🇪🇸', phone: '34' },
  { name: 'França', code: 'FR', emoji: '🇫🇷', phone: '33' },
  { name: 'Alemanha', code: 'DE', emoji: '🇩🇪', phone: '49' },
  { name: 'Itália', code: 'IT', emoji: '🇮🇹', phone: '39' },
  { name: 'Reino Unido', code: 'GB', emoji: '🇬🇧', phone: '44' },
  { name: 'Canadá', code: 'CA', emoji: '🇨🇦', phone: '1' },
  { name: 'Austrália', code: 'AU', emoji: '🇦🇺', phone: '61' },
  { name: 'Japão', code: 'JP', emoji: '🇯🇵', phone: '81' },
  { name: 'China', code: 'CN', emoji: '🇨🇳', phone: '86' },
  { name: 'Índia', code: 'IN', emoji: '🇮🇳', phone: '91' },
  { name: 'México', code: 'MX', emoji: '🇲🇽', phone: '52' },
  { name: 'Argentina', code: 'AR', emoji: '🇦🇷', phone: '54' },
  { name: 'Chile', code: 'CL', emoji: '🇨🇱', phone: '56' },
  { name: 'Colômbia', code: 'CO', emoji: '🇨🇴', phone: '57' },
  { name: 'Peru', code: 'PE', emoji: '🇵🇪', phone: '51' },
  { name: 'Venezuela', code: 'VE', emoji: '🇻🇪', phone: '58' },
  { name: 'Uruguai', code: 'UY', emoji: '🇺🇾', phone: '598' },
  { name: 'Paraguai', code: 'PY', emoji: '🇵🇾', phone: '595' },
  { name: 'Bolívia', code: 'BO', emoji: '🇧🇴', phone: '591' },
  { name: 'Equador', code: 'EC', emoji: '🇪🇨', phone: '593' },
  { name: 'África do Sul', code: 'ZA', emoji: '🇿🇦', phone: '27' },
  { name: 'Angola', code: 'AO', emoji: '🇦🇴', phone: '244' },
  { name: 'Moçambique', code: 'MZ', emoji: '🇲🇿', phone: '258' },
  { name: 'Cabo Verde', code: 'CV', emoji: '🇨🇻', phone: '238' },
  { name: 'Guiné-Bissau', code: 'GW', emoji: '🇬🇼', phone: '245' },
  { name: 'São Tomé e Príncipe', code: 'ST', emoji: '🇸🇹', phone: '239' },
  { name: 'Timor-Leste', code: 'TL', emoji: '🇹🇱', phone: '670' },
  { name: 'Macau', code: 'MO', emoji: '🇲🇴', phone: '853' }
];